name: pynguin-workbench

services:
  pynguin:
    container_name: pynguin
    image: pynguin:latest
    build:
      context: pynguin
      dockerfile: docker/Dockerfile
    command: $COMMAND
    volumes:
      - ./input:/input:ro
      - ./output:/output:rw
      - ./package:/package:ro
